version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: neobank-postgres
    environment:
      POSTGRES_DB: neobank_db
      POSTGRES_USER: neobank
      POSTGRES_PASSWORD: neobank123
    ports:
      - "5432:5432"

  app:
    build: ./neobank-app
    container_name: neobank-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/neobank_db
      SPRING_DATASOURCE_USERNAME: neobank
      SPRING_DATASOURCE_PASSWORD: neobank123
